/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/about/': RouteRecordInfo<'/admin/about/', '/admin/about', Record<never, never>, Record<never, never>>,
    '/admin/comments/': RouteRecordInfo<'/admin/comments/', '/admin/comments', Record<never, never>, Record<never, never>>,
    '/admin/life/': RouteRecordInfo<'/admin/life/', '/admin/life', Record<never, never>, Record<never, never>>,
    '/admin/life/[slug]': RouteRecordInfo<'/admin/life/[slug]', '/admin/life/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/posts/': RouteRecordInfo<'/admin/posts/', '/admin/posts', Record<never, never>, Record<never, never>>,
    '/admin/posts/[slug]': RouteRecordInfo<'/admin/posts/[slug]', '/admin/posts/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/admin/projects/': RouteRecordInfo<'/admin/projects/', '/admin/projects', Record<never, never>, Record<never, never>>,
    '/admin/projects/[slug]': RouteRecordInfo<'/admin/projects/[slug]', '/admin/projects/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/admin/users/': RouteRecordInfo<'/admin/users/', '/admin/users', Record<never, never>, Record<never, never>>,
    '/blog/': RouteRecordInfo<'/blog/', '/blog', Record<never, never>, Record<never, never>>,
    '/blog/[slug]': RouteRecordInfo<'/blog/[slug]', '/blog/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/life/': RouteRecordInfo<'/life/', '/life', Record<never, never>, Record<never, never>>,
    '/life/[slug]': RouteRecordInfo<'/life/[slug]', '/life/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/[slug]': RouteRecordInfo<'/projects/[slug]', '/projects/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/simple': RouteRecordInfo<'/simple', '/simple', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
