# Generated by Django 5.2.9 on 2026-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL 标识"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("blog", "博客"),
                            ("projects", "项目"),
                            ("life", "生活"),
                            ("notes", "笔记"),
                        ],
                        default="blog",
                        max_length=20,
                        verbose_name="分类类型",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SEO 关键词"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "articles_count",
                    models.PositiveIntegerField(default=0, verbose_name="文章数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="categories__slug_9b1a28_idx"),
                    models.Index(
                        fields=["category_type"], name="categories__categor_51118c_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="categories__sort_or_ac4749_idx"
                    ),
                ],
            },
        ),
    ]
