# Generated by Django 5.2.9 on 2026-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL 标识"
                    ),
                ),
                ("description", models.TextField(max_length=1000, verbose_name="描述")),
                ("content", models.TextField(blank=True, verbose_name="内容")),
                (
                    "locale",
                    models.CharField(
                        choices=[("zh", "中文"), ("en", "英文")],
                        default="zh",
                        max_length=5,
                        verbose_name="语言",
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(default=0, verbose_name="阅读时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("featured", models.BooleanField(default=False, verbose_name="精选")),
                ("cover_image", models.URLField(blank=True, verbose_name="封面图")),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SEO 关键词"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="阅读量"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "stars",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Stars"
                    ),
                ),
                (
                    "forks",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Forks"
                    ),
                ),
                ("repo", models.URLField(blank=True, verbose_name="仓库地址")),
                ("demo", models.URLField(blank=True, verbose_name="演示地址")),
                (
                    "tech_stack",
                    models.JSONField(blank=True, null=True, verbose_name="技术栈"),
                ),
                (
                    "project_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "活跃"),
                            ("maintenance", "维护中"),
                            ("archived", "已归档"),
                        ],
                        max_length=20,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(verbose_name="版本号")),
                ("title", models.CharField(max_length=500, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("change_log", models.TextField(blank=True, verbose_name="变更说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "文章版本",
                "verbose_name_plural": "文章版本",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ArticleView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
            ],
            options={
                "verbose_name": "阅读记录",
                "verbose_name_plural": "阅读记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
