# Generated by Django 5.2.9 on 2026-02-03 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        ("categories", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="categories.category",
                verbose_name="分类",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="tags.tag", verbose_name="标签"
            ),
        ),
        migrations.AddField(
            model_name="articleversion",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="articles.article",
                verbose_name="文章",
            ),
        ),
        migrations.AddField(
            model_name="articleversion",
            name="edited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="编辑者",
            ),
        ),
        migrations.AddField(
            model_name="articleview",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="articles.article",
                verbose_name="文章",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="articles_ar_slug_452037_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["status"], name="articles_ar_status_edb746_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["featured"], name="articles_ar_feature_183843_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["locale"], name="articles_ar_locale_0191a7_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-published_at"], name="articles_ar_publish_c1a2fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-view_count"], name="articles_ar_view_co_f1b57c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleversion",
            index=models.Index(
                fields=["article", "-version_number"],
                name="articles_ar_article_1189eb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articleversion",
            unique_together={("article", "version_number")},
        ),
        migrations.AddIndex(
            model_name="articleview",
            index=models.Index(
                fields=["article", "-created_at"], name="articles_ar_article_4017e1_idx"
            ),
        ),
    ]
