# Generated by Django 5.2.9 on 2026-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="标签名称"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL 标识"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SEO 关键词"
                    ),
                ),
                (
                    "articles_count",
                    models.PositiveIntegerField(default=0, verbose_name="文章数量"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="颜色"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "ordering": ["-articles_count", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="tags_tag_slug_dcb0c2_idx"),
                    models.Index(fields=["name"], name="tags_tag_name_3fbe74_idx"),
                ],
            },
        ),
    ]
