# Generated by Django 5.2.9 on 2026-02-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "评论点赞",
                "verbose_name_plural": "评论点赞",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(blank=True, max_length=100, verbose_name="访客名称"),
                ),
                (
                    "guest_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="访客邮箱"),
                ),
                ("guest_url", models.URLField(blank=True, verbose_name="访客网站")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "is_markdown",
                    models.BooleanField(default=True, verbose_name="Markdown 格式"),
                ),
                (
                    "giscus_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Giscus ID"
                    ),
                ),
                (
                    "giscus_discussion_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Giscus Discussion ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("spam", "垃圾评论"),
                            ("deleted", "已删除"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核通过时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="articles.article",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "ordering": ["-created_at"],
            },
        ),
    ]
