# Generated by Django 5.2.9 on 2026-02-03 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comments.comment",
                verbose_name="父评论",
            ),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="comments.comment",
                verbose_name="评论",
            ),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["article", "-created_at"], name="comments_co_article_7b228c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "-created_at"], name="comments_co_author__3265ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["status"], name="comments_co_status_2720ea_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent"], name="comments_co_parent__fdf1ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(
                fields=["comment", "-created_at"], name="comments_co_comment_a860f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(
                fields=["user", "-created_at"], name="comments_co_user_id_392545_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together={("comment", "user")},
        ),
    ]
