# Generated by Django 5.2.9 on 2026-02-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_url",
            field=models.URLField(
                blank=True, help_text="GitHub 个人主页", verbose_name="GitHub"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="LinkedIn 个人主页", verbose_name="LinkedIn"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.JSONField(
                blank=True, default=dict, help_text="技能栈数据", verbose_name="技能"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="timeline",
            field=models.JSONField(
                blank=True, default=list, help_text="个人经历时间线", verbose_name="时间线"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_url",
            field=models.URLField(
                blank=True, help_text="Twitter 个人主页", verbose_name="Twitter"
            ),
        ),
    ]
