# Generated by Django 5.2.9 on 2026-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_github_url_user_linkedin_url_user_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="story",
            field=models.TextField(
                blank=True, help_text="个人经历故事，支持 Markdown", verbose_name="我的故事"
            ),
        ),
    ]
