# Generated by Django 5.2.9 on 2026-02-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        ("categories", "0001_initial"),
        ("comments", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="阅读量"),
                ),
                (
                    "view_count_unique",
                    models.PositiveIntegerField(default=0, verbose_name="独立访客数"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "share_count",
                    models.PositiveIntegerField(default=0, verbose_name="分享数"),
                ),
                (
                    "bookmark_count",
                    models.PositiveIntegerField(default=0, verbose_name="收藏数"),
                ),
                ("hot_score", models.FloatField(default=0, verbose_name="热度分数")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="articles.article",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章统计",
                "verbose_name_plural": "文章统计",
            },
        ),
        migrations.CreateModel(
            name="CategoryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "articles_count",
                    models.PositiveIntegerField(default=0, verbose_name="文章数"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="总阅读量"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="categories.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类统计",
                "verbose_name_plural": "分类统计",
                "ordering": ["-view_count"],
            },
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "articles_published",
                    models.PositiveIntegerField(default=0, verbose_name="已发布文章数"),
                ),
                (
                    "articles_draft",
                    models.PositiveIntegerField(default=0, verbose_name="草稿文章数"),
                ),
                (
                    "articles_created",
                    models.PositiveIntegerField(default=0, verbose_name="新增文章数"),
                ),
                (
                    "users_new",
                    models.PositiveIntegerField(default=0, verbose_name="新增用户数"),
                ),
                (
                    "users_total",
                    models.PositiveIntegerField(default=0, verbose_name="总用户数"),
                ),
                (
                    "comments_new",
                    models.PositiveIntegerField(default=0, verbose_name="新增评论数"),
                ),
                (
                    "comments_total",
                    models.PositiveIntegerField(default=0, verbose_name="总评论数"),
                ),
                (
                    "views_total",
                    models.PositiveIntegerField(default=0, verbose_name="总访问量"),
                ),
                (
                    "views_unique",
                    models.PositiveIntegerField(default=0, verbose_name="独立访客数"),
                ),
                (
                    "likes_total",
                    models.PositiveIntegerField(default=0, verbose_name="总点赞数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "每日统计",
                "verbose_name_plural": "每日统计",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="stats_daily_date_06770a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PopularArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "每日"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                            ("all_time", "全部时间"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="周期",
                    ),
                ),
                (
                    "article_ids",
                    models.JSONField(default=list, verbose_name="文章 ID 列表"),
                ),
                ("cached_at", models.DateTimeField(auto_now=True, verbose_name="缓存时间")),
            ],
            options={
                "verbose_name": "热门文章",
                "verbose_name_plural": "热门文章",
                "indexes": [
                    models.Index(
                        fields=["period"], name="stats_popul_period_6a1182_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TagStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "articles_count",
                    models.PositiveIntegerField(default=0, verbose_name="文章数"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="总阅读量"),
                ),
                ("hot_score", models.FloatField(default=0, verbose_name="热度分数")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="tags.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "标签统计",
                "verbose_name_plural": "标签统计",
            },
        ),
        migrations.CreateModel(
            name="UserAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view_article", "浏览文章"),
                            ("like_article", "点赞文章"),
                            ("bookmark_article", "收藏文章"),
                            ("share_article", "分享文章"),
                            ("comment", "评论"),
                            ("like_comment", "点赞评论"),
                            ("search", "搜索"),
                        ],
                        max_length=30,
                        verbose_name="行为类型",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="元数据"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="articles.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="comments.comment",
                        verbose_name="评论",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户行为",
                "verbose_name_plural": "用户行为",
                "ordering": ["-created_at"],
            },
        ),
    ]
