# Generated by Django 5.2.9 on 2026-02-03 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="articlestats",
            index=models.Index(
                fields=["-hot_score"], name="stats_artic_hot_sco_8229d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlestats",
            index=models.Index(
                fields=["-view_count"], name="stats_artic_view_co_8e6dd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tagstats",
            index=models.Index(
                fields=["-hot_score"], name="stats_tagst_hot_sco_cfa33f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tagstats",
            index=models.Index(
                fields=["-articles_count"], name="stats_tagst_article_75a5b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraction",
            index=models.Index(
                fields=["user", "-created_at"], name="stats_usera_user_id_64eac8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraction",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="stats_usera_action__4673f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useraction",
            index=models.Index(
                fields=["article", "-created_at"], name="stats_usera_article_be46c2_idx"
            ),
        ),
    ]
